Repository GDSCTINT/hacktoberfest2022, pull requests merged in 2022-10, with the labels that each got.

#13 Create translation for portuguese
  translations/README.pt_br.md
Labels: hacktoberfest-accepted

#20 Update Array_Swap.c
  Array_Swap.c
Labels: spam

#26 Create Insertion Sort in Python
  InsetionSort.py
Labels: good first issue, hacktoberfest-accepted

#22 Update reverse_string.c
  reverse_string.c
Labels: good first issue, hacktoberfest-accepted

#29 Update BPlusTree.c
  BPlusTree.c
Labels: hacktoberfest-accepted

#34 palindromestring.java
  palindromestring.java
Labels: hacktoberfest-accepted

#33 Add uppercase conversion & bubble sort program
  Bubble_sort.c
  upper_conversion&showPalindrome.c
Labels: hacktoberfest-accepted

#32 Add files via upload
  bank management system.c.txt
Labels: hacktoberfest-accepted

#31 Added Subsets.cpp
  Subsets.cpp
Labels: hacktoberfest-accepted

#30 Update Circular Linked List.cpp
  CircularLinkedList.cpp
Labels: hacktoberfest-accepted

#36 Update q2.py
  q2.py
Labels: hacktoberfest-accepted

#37 Update reverse_string.c
  reverse_string.c
Labels: hacktoberfest-accepted

#38 Update palindrome.java
  palindrome.java
Labels: hacktoberfest-accepted

#44 Transversal of a Linkedd List
  TransversalofaLinkedList.py
Labels: hacktoberfest-accepted

#45 Create Scientific Calculator
  Scientific Calculator
Labels: hacktoberfest-accepted

#40 created plaindrome linkedlist file
  palindrome_linkedlist.java
Labels: enhancement, hacktoberfest-accepted

#39 Added Karatsuba code for larger number.
  Karatsuba_code.c
Labels: hacktoberfest-accepted

#41 added roatate linkedlist code
  rotate_linkedlist.java
Labels: hacktoberfest-accepted

#43 added binary tree pre order traversal code both iterative and recursive
  binarytree_preorder.java
Labels: hacktoberfest-accepted

#42 added binary tree level order traversal code
  binarytree_levelorder.java
Labels: hacktoberfest-accepted
